# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: true
dist: trusty
cache: packages

# Be strict when checking our package
warnings_are_errors: false

# nloptr R package requires libnlopt-dev to be installed, which requires trusty ubuntu
# phantomjs required for shinytest for VEGUI testing
before_install:
  - sudo apt-get update
  - sudo apt-get -y install libnlopt-dev
  - "export PHANTOMJS_VERSION=2.1.1"
  - "phantomjs --version"
  - "export PATH=$PWD/travis_phantomjs/phantomjs-$PHANTOMJS_VERSION-linux-x86_64/bin:$PATH"
  - "hash -r"
  - "phantomjs --version"
  - "if [ $(phantomjs --version) != $PHANTOMJS_VERSION ]; then rm -rf $PWD/travis_phantomjs; mkdir -p $PWD/travis_phantomjs; fi"
  - "if [ $(phantomjs --version) != $PHANTOMJS_VERSION ]; then wget https://github.com/Medium/phantomjs/releases/download/v$PHANTOMJS_VERSION/phantomjs-$PHANTOMJS_VERSION-linux-x86_64.tar.bz2 -O $PWD/travis_phantomjs/phantomjs-$PHANTOMJS_VERSION-linux-x86_64.tar.bz2; fi"
  - "if [ $(phantomjs --version) != $PHANTOMJS_VERSION ]; then tar -xvf $PWD/travis_phantomjs/phantomjs-$PHANTOMJS_VERSION-linux-x86_64.tar.bz2 -C $PWD/travis_phantomjs; fi"
  - "if [ $(phantomjs --version) != $PHANTOMJS_VERSION ]; then hash -r; fi"
  - "phantomjs --version"

# start by installing devtools
install:
  - Rscript -e 'install.packages(c("curl","devtools", "roxygen2", "stringr", "knitr"))'
  - Rscript -e 'devtools::install_bioc(c("BiocInstaller", "rhdf5"))'

# install and test framework, modules, models, GUI
script:
  - |
    cd sources/framework/visioneval
    Rscript -e 'devtools::install_deps(".")'
    Rscript -e 'devtools::check(".")'
    Rscript -e "tryCatch( source('tests/scripts/test.R') )"
    R CMD INSTALL .
    cd ../../..
    
    cd sources/modules/VE2001NHTS;
    Rscript -e 'devtools::install_deps(".")'
    Rscript -e 'devtools::check(".")'
    Rscript -e "tryCatch( source('tests/scripts/test.R') )"
    R CMD INSTALL .
    cd ../../..
       
    cd sources/modules/VELandUse;
    Rscript -e 'devtools::install_deps(".")'
    Rscript -e 'devtools::check(".")'
    Rscript -e "tryCatch( source('tests/scripts/test.R') )"
    R CMD INSTALL .
    cd ../../..
    
    cd sources/modules/VESimHouseholds
    Rscript -e 'devtools::install_deps(".")'
    Rscript -e 'devtools::check(".")'
    Rscript -e "tryCatch( source('tests/scripts/test.R') )"
    R CMD INSTALL .
    cd ../../..
    
    cd sources/modules/VESyntheticFirms
    Rscript -e 'devtools::install_deps(".")'
    Rscript -e 'devtools::check(".")'
    Rscript -e "tryCatch( source('tests/scripts/test.R') )"
    R CMD INSTALL .
    cd ../../..
    
    cd sources/modules/VETransportSupply
    Rscript -e 'devtools::install_deps(".")'
    Rscript -e 'devtools::check(".")'
    Rscript -e "tryCatch( source('tests/scripts/test.R') )"
    R CMD INSTALL .
    cd ../../..
    
    cd sources/modules/VETravelDemand
    Rscript -e 'devtools::install_deps(".")'
    Rscript -e 'devtools::check(".")'
    Rscript -e "tryCatch( source('tests/scripts/test.R') )"
    R CMD INSTALL .
    cd ../../..

    cd sources/modules/VETravelDemandMM
    Rscript -e 'devtools::install_deps(".")'
    Rscript -e 'devtools::check(".")'
    Rscript -e "tryCatch( source('tests/scripts/test.R') )"
    R CMD INSTALL .
    cd ../../..
    
    cd sources/modules/VEVehicleOwnership
    Rscript -e 'devtools::install_deps(".")'
    Rscript -e 'devtools::check(".")'
    Rscript -e "tryCatch( source('tests/scripts/test.R') )"
    R CMD INSTALL .
    cd ../../..
    
    cd sources/models/VERPAT
    Rscript -e "tryCatch( source('run_model.R') )"
    cd ../../..
    
    cd sources/models/VERSPM/Test1
    Rscript -e "tryCatch( source('run_model.R') )"
    cd ../../../..
    
    cd sources/VEGUI
    Rscript -e 'install.packages(c("shiny", "shinyjs", "shinyFiles", "data.table", "DT", "shinyBS", "future", "testit", "jsonlite", "shinyAce", "envDocument", "rhandsontable"))'
    Rscript -e 'devtools::install_github(c("tdhock/namedCapture", "trestletech/shinyTree", "rstudio/webdriver", "rstudio/shinytest"))'
    Rscript -e "tryCatch( source('run_vegui_test.R') )"
